version: '3.8'
services:
  django:
    build: ./django/django_project/
    container_name: djangoapp
    restart: always
    expose:
      - 8000
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    volumes:
      - ./django/django_project:/usr/src/app/
      - django_static_volume:/usr/src/app/static
      - django_media_volume:/usr/src/app/media
    networks:
      - myNetwork
    env_file:
      - ./.env

  node:
    build: ./reactapp
    container_name: reactapp
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./reactapp/package.json:/usr/src/app/package.json
      - ./reactapp/public/:/usr/src/app/public/
      - ./reactapp/src/:/usr/src/app/src/
    command: npm start
    depends_on:
      - django
    networks:
      - myNetwork

  postgres:
    image: postgres:15-alpine
    container_name: postgresdb
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=strong_password
      - POSTGRES_DB=django_db
    networks:
      - myNetwork
  
  nginx:
    build: ./nginx
    container_name: nginx_dtr
    networks:
      - myNetwork
    ports:
      - 8000:80
    depends_on:
      - django
    volumes:
      - django_static_volume:/home/src/app/static
      - django_media_volume:/home/src/app/media 

volumes:
  postgres_volume:
  django_static_volume:
  django_media_volume:

networks:
  myNetwork:
    driver: bridge