FROM node:18-alpine AS react-build

WORKDIR /app

COPY reactapp/package.json reactapp/package-lock.json ./
RUN npm ci

COPY reactapp/ .

ARG REACT_APP_API_BASE_URL=
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

RUN npm run build

FROM nginx:1.23-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=react-build /app/build /usr/share/nginx/html
