# Use the official Node Alpine image
FROM node:18-alpine as build
# Set the working directory
WORKDIR /usr/src/app
# Copy package manifest files
ADD *.json ./
# Install packages and dependencies from package.json
RUN npm install

# Copy the public and src directories.
# You could use COPY . ., but if node_modules is synced locally, the whole
# directory would be copied and that can cause problems.
ADD ./public ./public
ADD ./src ./src
